/**
 * Vitest configuration for `@karmaniverous/jeeves-scripts-core`.
 *
 * Runs with coverage (Decision 22) and excludes the bundled `template/`
 * build output (a copy of `packages/template`, regenerated by the build
 * script and covered by its own workspace's tests).
 *
 * @module vitest.config
 */

import { configDefaults, defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./test/setup.ts'],
    exclude: [
      ...configDefaults.exclude,
      '**/.rollup.cache/**',
      '**/dist/**',
      '**/template/**',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      exclude: ['**/template/**'],
    },
  },
});
